language : generic
sudo : require 
sevices :
  - docker

befora_install:
  - docker build -f Dockerfile.dev -t test/docker-react .

script :
  - docker run -e CI=true test/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-application"
  env: "DockerApplication-env"
  bucket_name: "elasticbeanstalk-us-east-2-586928785119"
  bucker_path: "docker-application"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY